import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Bungee } from "next/font/google";
import Navbar from "@/components/navigation/Navbar";
import "./globals.css";

const plusJakarta = Plus_Jakarta_Sans({ 
  subsets: ["latin"],
  weight: ['200','300','400', '500', '600', '700', '800',],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="{bg-[#020205] ${plusJakarta.className} overflow-hidden}">
        <nav className="flex justify-center">
    <Navbar/>
        </nav>
        {children}

      </body>
    </html>
  );
}